on:
  release:
    types: 
      - published

jobs:
  release-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
  
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17.x'
          distribution: adopt

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: |
          mkdir lib/application/l10n
          flutter pub get

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localizations
        run: |
          flutter gen-l10n
          flutter pub get --offline

      - name: FOSS-ify dependencies
        run: flutter pub remove --offline in_app_review

      - name: Write signing properties
        env:
          RUNNER_TEMP: ${{ runner.temp }}
          RELEASE_KEY_PROPERTIES_BASE64: ${{ secrets.RELEASE_KEY_PROPERTIES_BASE64 }}
        run: echo "$RELEASE_KEY_PROPERTIES_BASE64" | base64 -d | sed "s|{{temp}}|${RUNNER_TEMP}|g" > $GITHUB_WORKSPACE/android/key.properties

      - name: Write keystore
        env:
          RUNNER_TEMP: ${{ runner.temp }}
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}
        run: |
          echo $RELEASE_KEYSTORE_BASE64 | base64 -d > $RUNNER_TEMP/keystore.jks

      - name: Build APKs
        run: flutter build apk --flavor=foss -t lib/main.foss.dart --split-per-abi --obfuscate --split-debug-info=build/app/output/symbols

      - name: Rename assets for release
        working-directory: ${{ github.workspace }}/build/app/outputs/flutter-apk
        run: |
          mv app-armeabi-v7a-foss-release.apk arm_eabi.apk
          mv app-armeabi-v7a-foss-release.apk.sha1 arm_eabi.apk.sha1
          mv app-arm64-v8a-foss-release.apk arm_64.apk
          mv app-arm64-v8a-foss-release.apk.sha1 arm_64.apk.sha1
          mv app-arm64-x86_64-foss-release.apk x86_64.apk
          mv app-arm64-x86_64-foss-release.apk.sha1 x86_64.sha1
      
      - name: Upload assets
        working-directory: ${{ github.workspace }}/build/app/outputs/flutter-apk
        env: 
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} arm_eabi.apk arm_eabi.apk.sha1 arm_64.apk arm_64.apk.sha1 x86_64.apk x86_64.sha1
